services:
  agent-template:
    build: .
    container_name: agent-template
    env_file:
      - .env
    stdin_open: true
    ports:
      - "8000:8000"
    volumes:
      - ./reports:/app/reports
    develop:
      watch:
        - action: sync+restart
          path: ./src
          target: /app
    tty: true
    networks:
      - agents-net

networks:
  agents-net:
    external: true